# Generated by Django 3.0.4 on 2020-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year_low', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('year_high', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'ticker',
                'managed': False,
            },
        ),
    ]
