# Generated by Django 3.0.4 on 2020-03-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticker',
            options={'managed': True},
        ),
    ]
