# Generated by Django 3.0.4 on 2020-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='subscribe_options',
            field=models.IntegerField(default=0),
        ),
    ]
