# Generated by Django 3.0.4 on 2020-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_watchlist_subscribe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
