# Generated by Django 3.0.4 on 2020-04-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_auto_20200412_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.UserProfile'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Ticker'),
        ),
    ]
