# Generated by Django 3.0.4 on 2020-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_auto_20200308_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='sector',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
    ]
