# Generated by Django 3.0.4 on 2020-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_auto_20200308_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='year_high',
            new_name='day_high',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='year_low',
            new_name='day_low',
        ),
        migrations.AddField(
            model_name='ticker',
            name='fifty_two_week_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='fifty_two_week_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='industry',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
    ]
