# Generated by Django 3.0.4 on 2020-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_auto_20200425_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='annual_divident',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ex_divident_date',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='forwardpe_one_year',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ninety_day_avg_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='y1target',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
