# Generated by Django 3.0.4 on 2020-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_auto_20200426_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ex_divident_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
