# Generated by Django 3.0.4 on 2020-03-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_auto_20200308_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='exchange',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
