# Generated by Django 3.0.4 on 2020-03-21 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_ticker_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ticker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
