# Generated by Django 3.0.4 on 2020-05-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_auto_20200426_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expires',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ticker.Ticker'),
        ),
    ]
