# Generated by Django 3.0.4 on 2020-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0006_auto_20200505_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='last_trade_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='open_interest',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
