# Generated by Django 3.0.4 on 2020-03-22 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticker.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticker', '0007_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(choices=[(1, 'NORMAL'), (2, 'PREMIUM'), (3, 'GOLD')], default=ticker.utils.utils.UserTier['NORMAL'])),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticker.UserProfile'),
        ),
    ]
