# Generated by Django 3.0.4 on 2020-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0008_health'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='health',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='health',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='health',
            table='health',
        ),
    ]
