# Generated by Django 3.0.4 on 2020-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0010_ticker_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.IntegerField(default=0),
        ),
    ]
