# Generated by Django 3.0.4 on 2020-03-29 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0010_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='ask',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='options',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='options',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='iv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='options',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='volume',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
