# Generated by Django 3.0.4 on 2020-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0013_auto_20200526_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotewarehouse',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
    ]
