# Generated by Django 3.0.4 on 2020-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0014_auto_20200526_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotewarehouse',
            name='interval',
            field=models.IntegerField(default=0),
        ),
    ]
