# Generated by Django 3.0.4 on 2020-04-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0015_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='security_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
