# Generated by Django 3.0.4 on 2020-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0015_quotewarehouse_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotewarehouse',
            name='interval',
        ),
        migrations.AddField(
            model_name='quotewarehouse',
            name='period',
            field=models.CharField(default='1D', max_length=2),
        ),
    ]
