# Generated by Django 3.0.4 on 2020-06-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0016_auto_20200614_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotewarehouse',
            name='period',
            field=models.CharField(default='1D', max_length=3),
        ),
    ]
