# Generated by Django 3.0.4 on 2020-04-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0016_symbols_security_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='Symbols',
            new_name='Symbol',
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='option',
            table='options',
        ),
        migrations.AlterModelTable(
            name='ticker',
            table='tickers',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
        migrations.AlterModelTable(
            name='watchlist',
            table='watch_lists',
        ),
    ]
