# Generated by Django 3.0.4 on 2020-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0017_auto_20200614_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='name',
            field=models.CharField(blank=True, choices=[('CNBC_QUOTES', 'CNBC_QUOTES'), ('NASDAQ_QUOTES', 'NASDAQ_QUOTES'), ('YF_QUOTES', 'YF_QUOTES'), ('YF_OPTIONS', 'YF_OPTIONS'), ('CNBC', 'CNBC')], max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='status',
            field=models.IntegerField(blank=True, choices=[(500, '500'), (400, '400')], null=True),
        ),
    ]
